### ISSUE TITLE
Make all hover colors/actions and button colors consistent

### ISSUE THREAD

**Issue by dcochs3** [MagiShi/CrunchApp#59]
The hover colors of the edit and delete buttons on the Item Detail Page are different, I think.

Make sure all similar buttons (like all delete, action, and cancel) look similar to each other and behave the same on hover.

**Comment by phuynh35** [comment]
How's about making all buttons (except the Add New Item button on navbar) same color they are in but darker when hovered? Like the red button in pop-up. I saw that behavior is common in many websites (like Amazon, Facebook, Twitter, Github,...)

**Comment by phuynh35** [comment]
The Add New Item button on navbar looks good to me. It can be as it is.
