### ISSUE TITLE
As a new user, I want to register as a user so that I can edit items in the application, such as adding and deleting items.

### ISSUE THREAD

**Issue by dainryoo** [MagiShi/CrunchApp#9]
## Story/Task Details
- [x] Simple linking between html pages on button presses
- [x] Linking between html pages based on data
- [x] Register button in landing/intro page
- [ ] Profile info input
- [x] Submit registration button
- [x] Cancel registration button
- [x] Valid profile creation
- [x] Invalid profile creation
- [x] User is taken to home page after successful registration
- [x] Success notification
- [x] Failure notification

## Acceptance Scenarios
_Scenario: A new user wants to register as a student or admin._
- Given: that the new user is on the register page;
- When: the new user selects to register as a student or admin 
and they fill out the account’s profile details 
and they press the submit request button;
- Then: the new user sees a success message that says a request will be sent to an admin user for approval.

_Scenario: The user is already registered in the application._
- Given: that the user is on the register page;
- When: the user selects to register as a student or admin
and they fill out the account’s profile details 
and they press the submit request button;
- Then: the user sees a warning message that says an account already exists with that email
and they remain on the register page.

_Scenario: The user decides not to register in the application._
- Given: that the user is on the register page;
- When: the user presses the cancel button;
- Then: the user is taken back to the home page.

## Done Done Criteria

**Comment by MagiShi** [comment]
Profile details were put onto a separate goal/task on the iteration plan.
